"""ajouter la table click

Revision ID: 2b0ad4ac78e3
Revises: f1886750fef9
Create Date: 2025-05-10 19:36:41.630099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0ad4ac78e3'
down_revision = 'f1886750fef9'
branch_labels = None
depends_on = None


def upgrade():


    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('overview',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('overview',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)


    # ### end Alembic commands ###
