"""ajouter la table de recommendation

Revision ID: 8728defb2e22
Revises: 2b0ad4ac78e3
Create Date: 2025-05-11 15:43:21.847943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8728defb2e22'
down_revision = '2b0ad4ac78e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicked_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('clicked_at')

    # ### end Alembic commands ###
