"""ajout d'une autre route dans user_controller

Revision ID: f1886750fef9
Revises: 0cbaf8debbf1
Create Date: 2025-05-09 12:15:19.560236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1886750fef9'
down_revision = '0cbaf8debbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('likes', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=128), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_unique_constraint(None, ['firebase_uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('firebase_uid')

    # with op.batch_alter_table('likes', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)

    # ### end Alembic commands ###
