"""modifier le modelcomment afin que la motheode to_dict supporte user_id

Revision ID: fd9c5cacb3a2
Revises: 8728defb2e22
Create Date: 2025-05-28 21:18:49.415139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd9c5cacb3a2'
down_revision = '8728defb2e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicked_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_likes_comment_id')
        batch_op.drop_index('idx_comment_likes_user_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_comments_parent_id')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comments_parent_id', ['parent_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.create_index('idx_comment_likes_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_comment_likes_comment_id', ['comment_id'], unique=False)

    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('clicked_at')

    # ### end Alembic commands ###
