from .movie import Movie
from .like import Like
from .user import User
from .comment import Comment
from .watchlist import Watchlist
from .click import Click
from .recommendation import Recommendation
from .comment_like import CommentLike
from .notification import Notification
